---
name: Jackett
version: "v0.24.2508"
slug: hassio_jackett
description: An addon to add jackett to hassio
startup: application
boot: auto
url: "https://github.com/DmitryKadyshev/hassio-addons-jackett"
webui: "http://[HOST]:[PORT:9117]"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  9117/tcp: 9117
ports_description:
  9117/tcp: "WEB Config"
map:
  - addon_config:rw
