---
name: Jackett
version: "dev"
slug: hassio_jackett
description: An addon to add jackett to hassio
url: "https://github.com/DmitryKadyshev/hassio-addons-jackett"
ingress: true
ingress_port: 9117
ingress_stream: true
panel_icon: mdi:cloud-search
arch:
  - aarch64
  - amd64
init: false
ports:
  9118/tcp: 9118
ports_description:
  9118/tcp: "WEB Config"
map:
  - addon_config:rw
